In [1]:
import pandas as pd
import numpy as np
import nltk
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
import re
import string

In [16]:
true=pd.read_csv('True.csv')

In [17]:
true['label']=1

In [19]:
true.head()

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1

In [18]:
fake=pd.read_csv('Fake.csv')

In [20]:
fake['label']=0

In [21]:
fake.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [22]:
df=pd.concat([fake,true],axis=0)

In [23]:
df.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [24]:
df['new_text']=df['title']+' '+df['text']

In [25]:
df.head()

,title,text,subject,date,label,new_text
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0,Donald Trump Sends Out Embarrassing New Year’...
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0,Drunk Bragging Trump Staffer Started Russian ...
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0,Sheriff David Clarke Becomes An Internet Joke...
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0,Trump Is So Obsessed He Even Has Obama’s Name...
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0,Pope Francis Just Called Out Donald Trump Dur...

In [26]:
df.drop(columns=['subject','date','title','text'],inplace=True)

In [30]:
df.sample(5)

       label                                           new_text
10425      1  Clinton's surprise Michigan loss exposes risks...
1785       0   Local Fox Affiliate Just Gave Fox News A GIAN...
12209      1  Macron aiming for eurozone 'convergence' with ...
13401      1  Argentina blocks some activists from attending...
15232      1  U.N. says it believes Afghanistan air strike k...

In [31]:
df=df.sample(frac=1).reset_index(drop=True)

In [32]:
df

       label                                           new_text
0          1  Catalonia parliament votes for Oct. 1 referend...
1          1  U.S. drug enforcement chief to step down from ...
2          0  FREEDOM WATCH: “It’s Now Clear That FBI Direct...
3          0  REFUGEE BUSINESS IS CASH COW FOR LUTHERAN CHAR...
4          0  BUH-BYE! GLENN BECK Places Final Nail In His C...
...      ...                                                ...
44893      0  FLASHBACK: Hillary And Raunchy Actress Discuss...
44894      0  PITTSBURGH POLICE OFFICERS Boycotting Race Bai...
44895      1  Clinton leads Trump by 4 points in Washington ...
44896      1  Refugees' health problems in Greece mostly unm...
44897      1  After Somalia's deadliest bombing, a brother's...

[44898 rows x 2 columns]

In [33]:
df['new_text']=df['new_text'].str.lower()

In [34]:
df.head()

   label                                           new_text
0      1  catalonia parliament votes for oct. 1 referend...
1      1  u.s. drug enforcement chief to step down from ...
2      0  freedom watch: “it’s now clear that fbi direct...
3      0  refugee business is cash cow for lutheran char...
4      0  buh-bye! glenn beck places final nail in his c...

In [35]:
df['new_text'].unique()

array(['catalonia parliament votes for oct. 1 referendum on split from spain madrid (reuters) - catalonia s parliament voted on wednesday to hold an independence referendum on oct. 1, setting up a clash with the spanish government that has vowed to stop what it says would be an illegal vote. after 12 hours of often chaotic debate in the barcelona parliament, a majority voted for the referendum and the legal framework to set up a new state, under which the assembly would declare independence within 48 hours of a  yes  vote. lawmakers who opposed independence abandoned the chamber before the vote, with some leaving catalan flags in their empty seats. the winners, led by regional head carles puigdemont, sang the catalan national anthem once the votes were counted.   committed to freedom and democracy! we push on!  catalonia s deputy governor, oriol junqueras, tweeted after the vote. polls in the northeastern region show support for self-rule waning as spain s economy improves. but the majority of catalans do want the opportunity to vote on whether to split from spain. the government has asked the spanish constitutional court to declare the referendum law void as soon as it is approved by the regional parliament. the spanish constitution states that the country is indivisible.  what is happening in the catalan parliament is embarrassing, it s shameful,  deputy prime minister soraya saenz de santamaria told reporters. the details of the referendum, which would pose the question  do you want catalonia to be an independent republic?  to all spanish citizens living in catalonia, were revealed amid a tense atmosphere in the 135-seat regional parliament.  you will not split up spain, but you are breaking up catalonia,  alejandro fernandez of the ruling people s party (pp) told pro-independence lawmakers.  you re putting social harmony at risk.  the vote comes about three weeks after barcelona and a nearby town were struck by islamist attacks that killed 16 people and caused the catalan and spanish governments to present a brief united front. divisions reappeared as both sides squabbled over whether either could have prevented the attacks, and rallies against terrorism became politicized. crowds in barcelona booed spain s king felipe when he visited for one march. there will be no minimum turnout requirement to make the result of the referendum binding, puigdemont said in a recent briefing. ballot boxes, voting papers and an electoral census are at the ready, he said. spanish prime minister mariano rajoy told a news conference on monday the government would come down with all the force of the law to ensure no referendum would go ahead. courts have already suspended from office and leveled millions of euros in fines at catalan politicians who organized a non-binding referendum in 2014, which returned a  yes  vote on a low turnout. ',
       'u.s. drug enforcement chief to step down from agency (reuters) - the u.s. drug enforcement administration’s acting director on tuesday said that he will be leaving his post, two months after he criticized republican president donald trump for telling law enforcement officers not to be “too nice” to suspects. acting director chuck rosenberg, a holdover from democratic president barack obama’s administration, told the agency’s staff in an internal email that he will be leaving his position effective oct. 1. “this is a remarkable agency - full of remarkable people - and i am honored to have been a small part of it,” rosenberg said in the message, which was reviewed by reuters. it was unclear who would replace rosenberg. the news was first reported by the washington post.  a spokesman for the dea confirmed rosenberg’s resignation. rosenberg had been leading the dea in an acting capacity since 2015. before joining the agency, he served as chief of staff to former fbi director james comey, who trump fired in may.  rosenberg generated headlines earlier this year after he wrote an agency-wide email in late july challenging comments by trump suggesting officers do away with practices like protecting the head of a suspect being put into a patrol car. citing “an obligation to speak out when something is wrong,” rosenberg said trump’s remarks, delivered in new york the previous day, “condoned police misconduct regarding the treatment of individuals placed under arrest by law enforcement.” he leaves the agency at a time when the dea is grappling with the ongoing opioid drug epidemic, which has become a major law enforcement focus of the u.s. justice department. opioids, including prescription painkillers and heroin, killed more than 33,000 people in the united states in 2015, more than any year on record, according to the u.s. centers for disease control and prevention. “opioids such as heroin and fentanyl - and diverted prescription pain pills - are killing people in this country at a horrifying rate,” rosenberg said in december. “we face a public health crisis of historic proportions.” ',
       'freedom watch: “it’s now clear that fbi director comey was not honest with the committee”…”all those people on the left have just eaten a lot of crow” [video] freedom watch: fbi director comey lied to house intelligence committee about surveillance of trumpnunes pic.twitter.com/zzjjpdaivn  pamela moore (@pamela_moore13) march 22, 2017here is house intel chair rep devin nunes  press conference in its entirety:https://www.youtube.com/watch?v=pyr_oqbxth0&feature=youtu.be',
       ...,
       'clinton leads trump by 4 points in washington post: abc news poll washington (reuters) - democratic presidential nominee hillary clinton leads republican donald trump by 4 percentage points in a four-war race for the nov. 8 election, according to a washington post-abc news opinion poll of likely voters released on friday. clinton had 47 percent support compared with trump’s 43 percent in the poll conducted from monday to thursday, the post said. it said clinton’s lead was up from 3 points in the previous day’s poll but still “within the range of sampling error.”  ',
       "refugees' health problems in greece mostly unmet: medical charity athens (reuters) - refugees and migrants in greece receive little or no medical care for most health problems they face and fewer than half of those pregnant had access to maternal care, aid group doctors of the world said on tuesday. about 60,000 migrants and refugees are stranded in greece, most in overcrowded camps with unsanitary conditions. more than half of this year s 20,000 arrivals were women and children, united nations data shows.  doctors of the world interviewed over 14,000 women treated at its clinics in greece over three years and found fewer than 47 percent had access to antenatal care before it intervened. it also found as many as 72 percent of the health problems refugees faced were treated  inadequately  or not at all.   while most countries offer new arrivals some kind of medical screening, the quality was  questionable  and overlooked mental health problems, the charity said. often, women did not seek medical care because they were unaware of their rights, they found the healthcare system too complex or they were afraid of being arrested or discriminated against. limited resources and lack of access to services such as translators also posed practical obstacles.  every mother deserves good care before, during and post pregnancy. their residential status should not affect this basic right,  said nikitas kanakis, head of doctors of the world greece. the charity, together with healthcare company msd, known in the united states as merck, is implementing a two-year initiative aimed at providing maternal healthcare services to pregnant women and babies from vulnerable populations in greece. asylum seekers in greece have free access to hospitals and medical care but the public health system, already battered by years of economic crisis, is struggling to cope with the numbers.  adult migrants without documents only have access to emergency care unless they are considered  vulnerable .  access to quality maternal healthcare can save lives, yet across europe the most vulnerable pregnant women are still facing challenges in accessing this basic care,  said mary-ann etiebet, director of msd for mothers.  a lack of antenatal care to prevent and identify conditions that may harm the fetus or mother increases the risk of complications during childbirth or passing on diseases such as hiv or hepatitis b, the world health organisation says.  we must work together this address this issue before it escalates further,  etiebet said. (the story is refiled to clarify msd name in paragraph 8) ",
       "after somalia's deadliest bombing, a brother's desperate search mogadishu (reuters) - when somalia s deadliest truck bomb exploded on saturday, abdi ali ibrahim raced to the smoking crater just meters from where his beloved sister asha had a small business selling fuel. the truck had detonated next to a fuel tanker causing a huge fireball and the road was strewn with body parts. hopeful that asha, a pregnant mother-of-two, may have been injured and taken away by ambulance, ibrahim embarked on a frantic round of mogadishu s hospitals, starting with the biggest, madina.  i found many dead bodies, injured ones, body parts and burned bodies that were horribly shrunken. she was not there,  he told reuters as he sat hunched on a bench.  for two days ibrahim clung to the hope that 44-year-old asha had somehow survived the twin bombings that killed more than 300 people, the worst such attack in somalia s history. the bombings were similar to others claimed by al qaeda-linked al shabaab insurgents although the militants have yet to claim saturday s attacks. experts say the target may have been nearby government buildings, but the bomb went off too early. rushing from hospital to hospital, ibrahim was nauseated by the piles of burned flesh, but also tormented by the slim possibility his sister and her unborn baby might have survived and be in pain somewhere needing his help. finally, ibrahim returned to the scene where asha sold fuel.  just three meters away from where she sat, i saw a dark hole blown by the truck bomb. i could see sacks laid by the road upon which police placed organs, heads, limbs,  ibrahim said.   i saw her hand on a stone under a tree. it was her hand and it had the ring on her finger.  ibrahim took the hand to his elderly mother. he said she cried so hard that at first her words were inaudible to the crowd of relatives pressing around her.  she touched the hand three times and said,  this is the hand of my daughter, i am sure. this is the ring on her finger ... go and bury her .  as the scale of the attack became clear, president mohamed abdullahi farmaajo ordered three days of national mourning, doctors begged for blood donations, and the city s overstretched ambulance workers who had toiled to save the injured found time to begin ferrying the dead to the morgue. mass burials of unidentifiable bodies began, the blackened corpses wrapped in white sheets. perhaps one of them was asha.  that gave ibrahim and asha s children from her first marriage, a 21-year-old son and 23-year-old daughter, a new problem. could they conduct a funeral service for a hand if they could not find a body?  i asked many clerics how i should bury a hand,  ibrahim said.  some said funeral prayers must be conducted over the hand before burial. others rejected my idea and said no funeral prayer could be given for a body part.    finally i washed the hand, wrapped it in a piece of white shroud and buried it in a grave.   the dilemma is becoming more and more common. al shabaab is using bigger and bigger bombs. in 2016, 723 somalis were killed in 395 bomb attacks, according to nairobi-based think-tank sahan research, up from 193 deaths in 265 attacks in 2015. this year will probably be another grim record in the horn of africa nation, which has been riven by civil war since 1991. according to think-tank sahan, 40 percent of those killed last year and more than half of the injured were civilians.  the islamist insurgency that began in 2007 has been steadily losing ground since it was driven out of the capital mogadishu in 2011 but its ability to mount devastating attacks remains. ibrahim said he was distraught when he first saw asha s hand but is glad now that he found it.  i am satisfied because i know my sister has died,  he said.  there are many people who have not even found a single piece of their missing loved ones.  "],
      dtype=object)

In [36]:
import re

def url(text):
    return re.sub(r'http\S+|www\S+', '', text)

df['new_text'] = df['new_text'].apply(url)

In [37]:
df['new_text'].unique()

array(['catalonia parliament votes for oct. 1 referendum on split from spain madrid (reuters) - catalonia s parliament voted on wednesday to hold an independence referendum on oct. 1, setting up a clash with the spanish government that has vowed to stop what it says would be an illegal vote. after 12 hours of often chaotic debate in the barcelona parliament, a majority voted for the referendum and the legal framework to set up a new state, under which the assembly would declare independence within 48 hours of a  yes  vote. lawmakers who opposed independence abandoned the chamber before the vote, with some leaving catalan flags in their empty seats. the winners, led by regional head carles puigdemont, sang the catalan national anthem once the votes were counted.   committed to freedom and democracy! we push on!  catalonia s deputy governor, oriol junqueras, tweeted after the vote. polls in the northeastern region show support for self-rule waning as spain s economy improves. but the majority of catalans do want the opportunity to vote on whether to split from spain. the government has asked the spanish constitutional court to declare the referendum law void as soon as it is approved by the regional parliament. the spanish constitution states that the country is indivisible.  what is happening in the catalan parliament is embarrassing, it s shameful,  deputy prime minister soraya saenz de santamaria told reporters. the details of the referendum, which would pose the question  do you want catalonia to be an independent republic?  to all spanish citizens living in catalonia, were revealed amid a tense atmosphere in the 135-seat regional parliament.  you will not split up spain, but you are breaking up catalonia,  alejandro fernandez of the ruling people s party (pp) told pro-independence lawmakers.  you re putting social harmony at risk.  the vote comes about three weeks after barcelona and a nearby town were struck by islamist attacks that killed 16 people and caused the catalan and spanish governments to present a brief united front. divisions reappeared as both sides squabbled over whether either could have prevented the attacks, and rallies against terrorism became politicized. crowds in barcelona booed spain s king felipe when he visited for one march. there will be no minimum turnout requirement to make the result of the referendum binding, puigdemont said in a recent briefing. ballot boxes, voting papers and an electoral census are at the ready, he said. spanish prime minister mariano rajoy told a news conference on monday the government would come down with all the force of the law to ensure no referendum would go ahead. courts have already suspended from office and leveled millions of euros in fines at catalan politicians who organized a non-binding referendum in 2014, which returned a  yes  vote on a low turnout. ',
       'u.s. drug enforcement chief to step down from agency (reuters) - the u.s. drug enforcement administration’s acting director on tuesday said that he will be leaving his post, two months after he criticized republican president donald trump for telling law enforcement officers not to be “too nice” to suspects. acting director chuck rosenberg, a holdover from democratic president barack obama’s administration, told the agency’s staff in an internal email that he will be leaving his position effective oct. 1. “this is a remarkable agency - full of remarkable people - and i am honored to have been a small part of it,” rosenberg said in the message, which was reviewed by reuters. it was unclear who would replace rosenberg. the news was first reported by the washington post.  a spokesman for the dea confirmed rosenberg’s resignation. rosenberg had been leading the dea in an acting capacity since 2015. before joining the agency, he served as chief of staff to former fbi director james comey, who trump fired in may.  rosenberg generated headlines earlier this year after he wrote an agency-wide email in late july challenging comments by trump suggesting officers do away with practices like protecting the head of a suspect being put into a patrol car. citing “an obligation to speak out when something is wrong,” rosenberg said trump’s remarks, delivered in new york the previous day, “condoned police misconduct regarding the treatment of individuals placed under arrest by law enforcement.” he leaves the agency at a time when the dea is grappling with the ongoing opioid drug epidemic, which has become a major law enforcement focus of the u.s. justice department. opioids, including prescription painkillers and heroin, killed more than 33,000 people in the united states in 2015, more than any year on record, according to the u.s. centers for disease control and prevention. “opioids such as heroin and fentanyl - and diverted prescription pain pills - are killing people in this country at a horrifying rate,” rosenberg said in december. “we face a public health crisis of historic proportions.” ',
       'freedom watch: “it’s now clear that fbi director comey was not honest with the committee”…”all those people on the left have just eaten a lot of crow” [video] freedom watch: fbi director comey lied to house intelligence committee about surveillance of trumpnunes pic.twitter.com/zzjjpdaivn  pamela moore (@pamela_moore13) march 22, 2017here is house intel chair rep devin nunes  press conference in its entirety:',
       ...,
       'clinton leads trump by 4 points in washington post: abc news poll washington (reuters) - democratic presidential nominee hillary clinton leads republican donald trump by 4 percentage points in a four-war race for the nov. 8 election, according to a washington post-abc news opinion poll of likely voters released on friday. clinton had 47 percent support compared with trump’s 43 percent in the poll conducted from monday to thursday, the post said. it said clinton’s lead was up from 3 points in the previous day’s poll but still “within the range of sampling error.”  ',
       "refugees' health problems in greece mostly unmet: medical charity athens (reuters) - refugees and migrants in greece receive little or no medical care for most health problems they face and fewer than half of those pregnant had access to maternal care, aid group doctors of the world said on tuesday. about 60,000 migrants and refugees are stranded in greece, most in overcrowded camps with unsanitary conditions. more than half of this year s 20,000 arrivals were women and children, united nations data shows.  doctors of the world interviewed over 14,000 women treated at its clinics in greece over three years and found fewer than 47 percent had access to antenatal care before it intervened. it also found as many as 72 percent of the health problems refugees faced were treated  inadequately  or not at all.   while most countries offer new arrivals some kind of medical screening, the quality was  questionable  and overlooked mental health problems, the charity said. often, women did not seek medical care because they were unaware of their rights, they found the healthcare system too complex or they were afraid of being arrested or discriminated against. limited resources and lack of access to services such as translators also posed practical obstacles.  every mother deserves good care before, during and post pregnancy. their residential status should not affect this basic right,  said nikitas kanakis, head of doctors of the world greece. the charity, together with healthcare company msd, known in the united states as merck, is implementing a two-year initiative aimed at providing maternal healthcare services to pregnant women and babies from vulnerable populations in greece. asylum seekers in greece have free access to hospitals and medical care but the public health system, already battered by years of economic crisis, is struggling to cope with the numbers.  adult migrants without documents only have access to emergency care unless they are considered  vulnerable .  access to quality maternal healthcare can save lives, yet across europe the most vulnerable pregnant women are still facing challenges in accessing this basic care,  said mary-ann etiebet, director of msd for mothers.  a lack of antenatal care to prevent and identify conditions that may harm the fetus or mother increases the risk of complications during childbirth or passing on diseases such as hiv or hepatitis b, the world health organisation says.  we must work together this address this issue before it escalates further,  etiebet said. (the story is refiled to clarify msd name in paragraph 8) ",
       "after somalia's deadliest bombing, a brother's desperate search mogadishu (reuters) - when somalia s deadliest truck bomb exploded on saturday, abdi ali ibrahim raced to the smoking crater just meters from where his beloved sister asha had a small business selling fuel. the truck had detonated next to a fuel tanker causing a huge fireball and the road was strewn with body parts. hopeful that asha, a pregnant mother-of-two, may have been injured and taken away by ambulance, ibrahim embarked on a frantic round of mogadishu s hospitals, starting with the biggest, madina.  i found many dead bodies, injured ones, body parts and burned bodies that were horribly shrunken. she was not there,  he told reuters as he sat hunched on a bench.  for two days ibrahim clung to the hope that 44-year-old asha had somehow survived the twin bombings that killed more than 300 people, the worst such attack in somalia s history. the bombings were similar to others claimed by al qaeda-linked al shabaab insurgents although the militants have yet to claim saturday s attacks. experts say the target may have been nearby government buildings, but the bomb went off too early. rushing from hospital to hospital, ibrahim was nauseated by the piles of burned flesh, but also tormented by the slim possibility his sister and her unborn baby might have survived and be in pain somewhere needing his help. finally, ibrahim returned to the scene where asha sold fuel.  just three meters away from where she sat, i saw a dark hole blown by the truck bomb. i could see sacks laid by the road upon which police placed organs, heads, limbs,  ibrahim said.   i saw her hand on a stone under a tree. it was her hand and it had the ring on her finger.  ibrahim took the hand to his elderly mother. he said she cried so hard that at first her words were inaudible to the crowd of relatives pressing around her.  she touched the hand three times and said,  this is the hand of my daughter, i am sure. this is the ring on her finger ... go and bury her .  as the scale of the attack became clear, president mohamed abdullahi farmaajo ordered three days of national mourning, doctors begged for blood donations, and the city s overstretched ambulance workers who had toiled to save the injured found time to begin ferrying the dead to the morgue. mass burials of unidentifiable bodies began, the blackened corpses wrapped in white sheets. perhaps one of them was asha.  that gave ibrahim and asha s children from her first marriage, a 21-year-old son and 23-year-old daughter, a new problem. could they conduct a funeral service for a hand if they could not find a body?  i asked many clerics how i should bury a hand,  ibrahim said.  some said funeral prayers must be conducted over the hand before burial. others rejected my idea and said no funeral prayer could be given for a body part.    finally i washed the hand, wrapped it in a piece of white shroud and buried it in a grave.   the dilemma is becoming more and more common. al shabaab is using bigger and bigger bombs. in 2016, 723 somalis were killed in 395 bomb attacks, according to nairobi-based think-tank sahan research, up from 193 deaths in 265 attacks in 2015. this year will probably be another grim record in the horn of africa nation, which has been riven by civil war since 1991. according to think-tank sahan, 40 percent of those killed last year and more than half of the injured were civilians.  the islamist insurgency that began in 2007 has been steadily losing ground since it was driven out of the capital mogadishu in 2011 but its ability to mount devastating attacks remains. ibrahim said he was distraught when he first saw asha s hand but is glad now that he found it.  i am satisfied because i know my sister has died,  he said.  there are many people who have not even found a single piece of their missing loved ones.  "],
      dtype=object)

In [38]:
def pun(text):
    return re.sub(r'[^a-z0-9\s]','',text)

In [39]:
df['new_text']=df['new_text'].apply(pun)

In [40]:
df['new_text'].unique()

array(['catalonia parliament votes for oct 1 referendum on split from spain madrid reuters  catalonia s parliament voted on wednesday to hold an independence referendum on oct 1 setting up a clash with the spanish government that has vowed to stop what it says would be an illegal vote after 12 hours of often chaotic debate in the barcelona parliament a majority voted for the referendum and the legal framework to set up a new state under which the assembly would declare independence within 48 hours of a  yes  vote lawmakers who opposed independence abandoned the chamber before the vote with some leaving catalan flags in their empty seats the winners led by regional head carles puigdemont sang the catalan national anthem once the votes were counted   committed to freedom and democracy we push on  catalonia s deputy governor oriol junqueras tweeted after the vote polls in the northeastern region show support for selfrule waning as spain s economy improves but the majority of catalans do want the opportunity to vote on whether to split from spain the government has asked the spanish constitutional court to declare the referendum law void as soon as it is approved by the regional parliament the spanish constitution states that the country is indivisible  what is happening in the catalan parliament is embarrassing it s shameful  deputy prime minister soraya saenz de santamaria told reporters the details of the referendum which would pose the question  do you want catalonia to be an independent republic  to all spanish citizens living in catalonia were revealed amid a tense atmosphere in the 135seat regional parliament  you will not split up spain but you are breaking up catalonia  alejandro fernandez of the ruling people s party pp told proindependence lawmakers  you re putting social harmony at risk  the vote comes about three weeks after barcelona and a nearby town were struck by islamist attacks that killed 16 people and caused the catalan and spanish governments to present a brief united front divisions reappeared as both sides squabbled over whether either could have prevented the attacks and rallies against terrorism became politicized crowds in barcelona booed spain s king felipe when he visited for one march there will be no minimum turnout requirement to make the result of the referendum binding puigdemont said in a recent briefing ballot boxes voting papers and an electoral census are at the ready he said spanish prime minister mariano rajoy told a news conference on monday the government would come down with all the force of the law to ensure no referendum would go ahead courts have already suspended from office and leveled millions of euros in fines at catalan politicians who organized a nonbinding referendum in 2014 which returned a  yes  vote on a low turnout ',
       'us drug enforcement chief to step down from agency reuters  the us drug enforcement administrations acting director on tuesday said that he will be leaving his post two months after he criticized republican president donald trump for telling law enforcement officers not to be too nice to suspects acting director chuck rosenberg a holdover from democratic president barack obamas administration told the agencys staff in an internal email that he will be leaving his position effective oct 1 this is a remarkable agency  full of remarkable people  and i am honored to have been a small part of it rosenberg said in the message which was reviewed by reuters it was unclear who would replace rosenberg the news was first reported by the washington post  a spokesman for the dea confirmed rosenbergs resignation rosenberg had been leading the dea in an acting capacity since 2015 before joining the agency he served as chief of staff to former fbi director james comey who trump fired in may  rosenberg generated headlines earlier this year after he wrote an agencywide email in late july challenging comments by trump suggesting officers do away with practices like protecting the head of a suspect being put into a patrol car citing an obligation to speak out when something is wrong rosenberg said trumps remarks delivered in new york the previous day condoned police misconduct regarding the treatment of individuals placed under arrest by law enforcement he leaves the agency at a time when the dea is grappling with the ongoing opioid drug epidemic which has become a major law enforcement focus of the us justice department opioids including prescription painkillers and heroin killed more than 33000 people in the united states in 2015 more than any year on record according to the us centers for disease control and prevention opioids such as heroin and fentanyl  and diverted prescription pain pills  are killing people in this country at a horrifying rate rosenberg said in december we face a public health crisis of historic proportions ',
       'freedom watch its now clear that fbi director comey was not honest with the committeeall those people on the left have just eaten a lot of crow video freedom watch fbi director comey lied to house intelligence committee about surveillance of trumpnunes pictwittercomzzjjpdaivn  pamela moore pamelamoore13 march 22 2017here is house intel chair rep devin nunes  press conference in its entirety',
       ...,
       'clinton leads trump by 4 points in washington post abc news poll washington reuters  democratic presidential nominee hillary clinton leads republican donald trump by 4 percentage points in a fourwar race for the nov 8 election according to a washington postabc news opinion poll of likely voters released on friday clinton had 47 percent support compared with trumps 43 percent in the poll conducted from monday to thursday the post said it said clintons lead was up from 3 points in the previous days poll but still within the range of sampling error  ',
       'refugees health problems in greece mostly unmet medical charity athens reuters  refugees and migrants in greece receive little or no medical care for most health problems they face and fewer than half of those pregnant had access to maternal care aid group doctors of the world said on tuesday about 60000 migrants and refugees are stranded in greece most in overcrowded camps with unsanitary conditions more than half of this year s 20000 arrivals were women and children united nations data shows  doctors of the world interviewed over 14000 women treated at its clinics in greece over three years and found fewer than 47 percent had access to antenatal care before it intervened it also found as many as 72 percent of the health problems refugees faced were treated  inadequately  or not at all   while most countries offer new arrivals some kind of medical screening the quality was  questionable  and overlooked mental health problems the charity said often women did not seek medical care because they were unaware of their rights they found the healthcare system too complex or they were afraid of being arrested or discriminated against limited resources and lack of access to services such as translators also posed practical obstacles  every mother deserves good care before during and post pregnancy their residential status should not affect this basic right  said nikitas kanakis head of doctors of the world greece the charity together with healthcare company msd known in the united states as merck is implementing a twoyear initiative aimed at providing maternal healthcare services to pregnant women and babies from vulnerable populations in greece asylum seekers in greece have free access to hospitals and medical care but the public health system already battered by years of economic crisis is struggling to cope with the numbers  adult migrants without documents only have access to emergency care unless they are considered  vulnerable   access to quality maternal healthcare can save lives yet across europe the most vulnerable pregnant women are still facing challenges in accessing this basic care  said maryann etiebet director of msd for mothers  a lack of antenatal care to prevent and identify conditions that may harm the fetus or mother increases the risk of complications during childbirth or passing on diseases such as hiv or hepatitis b the world health organisation says  we must work together this address this issue before it escalates further  etiebet said the story is refiled to clarify msd name in paragraph 8 ',
       'after somalias deadliest bombing a brothers desperate search mogadishu reuters  when somalia s deadliest truck bomb exploded on saturday abdi ali ibrahim raced to the smoking crater just meters from where his beloved sister asha had a small business selling fuel the truck had detonated next to a fuel tanker causing a huge fireball and the road was strewn with body parts hopeful that asha a pregnant motheroftwo may have been injured and taken away by ambulance ibrahim embarked on a frantic round of mogadishu s hospitals starting with the biggest madina  i found many dead bodies injured ones body parts and burned bodies that were horribly shrunken she was not there  he told reuters as he sat hunched on a bench  for two days ibrahim clung to the hope that 44yearold asha had somehow survived the twin bombings that killed more than 300 people the worst such attack in somalia s history the bombings were similar to others claimed by al qaedalinked al shabaab insurgents although the militants have yet to claim saturday s attacks experts say the target may have been nearby government buildings but the bomb went off too early rushing from hospital to hospital ibrahim was nauseated by the piles of burned flesh but also tormented by the slim possibility his sister and her unborn baby might have survived and be in pain somewhere needing his help finally ibrahim returned to the scene where asha sold fuel  just three meters away from where she sat i saw a dark hole blown by the truck bomb i could see sacks laid by the road upon which police placed organs heads limbs  ibrahim said   i saw her hand on a stone under a tree it was her hand and it had the ring on her finger  ibrahim took the hand to his elderly mother he said she cried so hard that at first her words were inaudible to the crowd of relatives pressing around her  she touched the hand three times and said  this is the hand of my daughter i am sure this is the ring on her finger  go and bury her   as the scale of the attack became clear president mohamed abdullahi farmaajo ordered three days of national mourning doctors begged for blood donations and the city s overstretched ambulance workers who had toiled to save the injured found time to begin ferrying the dead to the morgue mass burials of unidentifiable bodies began the blackened corpses wrapped in white sheets perhaps one of them was asha  that gave ibrahim and asha s children from her first marriage a 21yearold son and 23yearold daughter a new problem could they conduct a funeral service for a hand if they could not find a body  i asked many clerics how i should bury a hand  ibrahim said  some said funeral prayers must be conducted over the hand before burial others rejected my idea and said no funeral prayer could be given for a body part    finally i washed the hand wrapped it in a piece of white shroud and buried it in a grave   the dilemma is becoming more and more common al shabaab is using bigger and bigger bombs in 2016 723 somalis were killed in 395 bomb attacks according to nairobibased thinktank sahan research up from 193 deaths in 265 attacks in 2015 this year will probably be another grim record in the horn of africa nation which has been riven by civil war since 1991 according to thinktank sahan 40 percent of those killed last year and more than half of the injured were civilians  the islamist insurgency that began in 2007 has been steadily losing ground since it was driven out of the capital mogadishu in 2011 but its ability to mount devastating attacks remains ibrahim said he was distraught when he first saw asha s hand but is glad now that he found it  i am satisfied because i know my sister has died  he said  there are many people who have not even found a single piece of their missing loved ones  '],
      dtype=object)

In [41]:
def xtra(text):
    return re.sub(r'\s+', ' ', text).strip()

In [42]:
df['new_text']=df['new_text'].apply(xtra)

In [43]:
df['new_text'].unique()

array(['catalonia parliament votes for oct 1 referendum on split from spain madrid reuters catalonia s parliament voted on wednesday to hold an independence referendum on oct 1 setting up a clash with the spanish government that has vowed to stop what it says would be an illegal vote after 12 hours of often chaotic debate in the barcelona parliament a majority voted for the referendum and the legal framework to set up a new state under which the assembly would declare independence within 48 hours of a yes vote lawmakers who opposed independence abandoned the chamber before the vote with some leaving catalan flags in their empty seats the winners led by regional head carles puigdemont sang the catalan national anthem once the votes were counted committed to freedom and democracy we push on catalonia s deputy governor oriol junqueras tweeted after the vote polls in the northeastern region show support for selfrule waning as spain s economy improves but the majority of catalans do want the opportunity to vote on whether to split from spain the government has asked the spanish constitutional court to declare the referendum law void as soon as it is approved by the regional parliament the spanish constitution states that the country is indivisible what is happening in the catalan parliament is embarrassing it s shameful deputy prime minister soraya saenz de santamaria told reporters the details of the referendum which would pose the question do you want catalonia to be an independent republic to all spanish citizens living in catalonia were revealed amid a tense atmosphere in the 135seat regional parliament you will not split up spain but you are breaking up catalonia alejandro fernandez of the ruling people s party pp told proindependence lawmakers you re putting social harmony at risk the vote comes about three weeks after barcelona and a nearby town were struck by islamist attacks that killed 16 people and caused the catalan and spanish governments to present a brief united front divisions reappeared as both sides squabbled over whether either could have prevented the attacks and rallies against terrorism became politicized crowds in barcelona booed spain s king felipe when he visited for one march there will be no minimum turnout requirement to make the result of the referendum binding puigdemont said in a recent briefing ballot boxes voting papers and an electoral census are at the ready he said spanish prime minister mariano rajoy told a news conference on monday the government would come down with all the force of the law to ensure no referendum would go ahead courts have already suspended from office and leveled millions of euros in fines at catalan politicians who organized a nonbinding referendum in 2014 which returned a yes vote on a low turnout',
       'us drug enforcement chief to step down from agency reuters the us drug enforcement administrations acting director on tuesday said that he will be leaving his post two months after he criticized republican president donald trump for telling law enforcement officers not to be too nice to suspects acting director chuck rosenberg a holdover from democratic president barack obamas administration told the agencys staff in an internal email that he will be leaving his position effective oct 1 this is a remarkable agency full of remarkable people and i am honored to have been a small part of it rosenberg said in the message which was reviewed by reuters it was unclear who would replace rosenberg the news was first reported by the washington post a spokesman for the dea confirmed rosenbergs resignation rosenberg had been leading the dea in an acting capacity since 2015 before joining the agency he served as chief of staff to former fbi director james comey who trump fired in may rosenberg generated headlines earlier this year after he wrote an agencywide email in late july challenging comments by trump suggesting officers do away with practices like protecting the head of a suspect being put into a patrol car citing an obligation to speak out when something is wrong rosenberg said trumps remarks delivered in new york the previous day condoned police misconduct regarding the treatment of individuals placed under arrest by law enforcement he leaves the agency at a time when the dea is grappling with the ongoing opioid drug epidemic which has become a major law enforcement focus of the us justice department opioids including prescription painkillers and heroin killed more than 33000 people in the united states in 2015 more than any year on record according to the us centers for disease control and prevention opioids such as heroin and fentanyl and diverted prescription pain pills are killing people in this country at a horrifying rate rosenberg said in december we face a public health crisis of historic proportions',
       'freedom watch its now clear that fbi director comey was not honest with the committeeall those people on the left have just eaten a lot of crow video freedom watch fbi director comey lied to house intelligence committee about surveillance of trumpnunes pictwittercomzzjjpdaivn pamela moore pamelamoore13 march 22 2017here is house intel chair rep devin nunes press conference in its entirety',
       ...,
       'clinton leads trump by 4 points in washington post abc news poll washington reuters democratic presidential nominee hillary clinton leads republican donald trump by 4 percentage points in a fourwar race for the nov 8 election according to a washington postabc news opinion poll of likely voters released on friday clinton had 47 percent support compared with trumps 43 percent in the poll conducted from monday to thursday the post said it said clintons lead was up from 3 points in the previous days poll but still within the range of sampling error',
       'refugees health problems in greece mostly unmet medical charity athens reuters refugees and migrants in greece receive little or no medical care for most health problems they face and fewer than half of those pregnant had access to maternal care aid group doctors of the world said on tuesday about 60000 migrants and refugees are stranded in greece most in overcrowded camps with unsanitary conditions more than half of this year s 20000 arrivals were women and children united nations data shows doctors of the world interviewed over 14000 women treated at its clinics in greece over three years and found fewer than 47 percent had access to antenatal care before it intervened it also found as many as 72 percent of the health problems refugees faced were treated inadequately or not at all while most countries offer new arrivals some kind of medical screening the quality was questionable and overlooked mental health problems the charity said often women did not seek medical care because they were unaware of their rights they found the healthcare system too complex or they were afraid of being arrested or discriminated against limited resources and lack of access to services such as translators also posed practical obstacles every mother deserves good care before during and post pregnancy their residential status should not affect this basic right said nikitas kanakis head of doctors of the world greece the charity together with healthcare company msd known in the united states as merck is implementing a twoyear initiative aimed at providing maternal healthcare services to pregnant women and babies from vulnerable populations in greece asylum seekers in greece have free access to hospitals and medical care but the public health system already battered by years of economic crisis is struggling to cope with the numbers adult migrants without documents only have access to emergency care unless they are considered vulnerable access to quality maternal healthcare can save lives yet across europe the most vulnerable pregnant women are still facing challenges in accessing this basic care said maryann etiebet director of msd for mothers a lack of antenatal care to prevent and identify conditions that may harm the fetus or mother increases the risk of complications during childbirth or passing on diseases such as hiv or hepatitis b the world health organisation says we must work together this address this issue before it escalates further etiebet said the story is refiled to clarify msd name in paragraph 8',
       'after somalias deadliest bombing a brothers desperate search mogadishu reuters when somalia s deadliest truck bomb exploded on saturday abdi ali ibrahim raced to the smoking crater just meters from where his beloved sister asha had a small business selling fuel the truck had detonated next to a fuel tanker causing a huge fireball and the road was strewn with body parts hopeful that asha a pregnant motheroftwo may have been injured and taken away by ambulance ibrahim embarked on a frantic round of mogadishu s hospitals starting with the biggest madina i found many dead bodies injured ones body parts and burned bodies that were horribly shrunken she was not there he told reuters as he sat hunched on a bench for two days ibrahim clung to the hope that 44yearold asha had somehow survived the twin bombings that killed more than 300 people the worst such attack in somalia s history the bombings were similar to others claimed by al qaedalinked al shabaab insurgents although the militants have yet to claim saturday s attacks experts say the target may have been nearby government buildings but the bomb went off too early rushing from hospital to hospital ibrahim was nauseated by the piles of burned flesh but also tormented by the slim possibility his sister and her unborn baby might have survived and be in pain somewhere needing his help finally ibrahim returned to the scene where asha sold fuel just three meters away from where she sat i saw a dark hole blown by the truck bomb i could see sacks laid by the road upon which police placed organs heads limbs ibrahim said i saw her hand on a stone under a tree it was her hand and it had the ring on her finger ibrahim took the hand to his elderly mother he said she cried so hard that at first her words were inaudible to the crowd of relatives pressing around her she touched the hand three times and said this is the hand of my daughter i am sure this is the ring on her finger go and bury her as the scale of the attack became clear president mohamed abdullahi farmaajo ordered three days of national mourning doctors begged for blood donations and the city s overstretched ambulance workers who had toiled to save the injured found time to begin ferrying the dead to the morgue mass burials of unidentifiable bodies began the blackened corpses wrapped in white sheets perhaps one of them was asha that gave ibrahim and asha s children from her first marriage a 21yearold son and 23yearold daughter a new problem could they conduct a funeral service for a hand if they could not find a body i asked many clerics how i should bury a hand ibrahim said some said funeral prayers must be conducted over the hand before burial others rejected my idea and said no funeral prayer could be given for a body part finally i washed the hand wrapped it in a piece of white shroud and buried it in a grave the dilemma is becoming more and more common al shabaab is using bigger and bigger bombs in 2016 723 somalis were killed in 395 bomb attacks according to nairobibased thinktank sahan research up from 193 deaths in 265 attacks in 2015 this year will probably be another grim record in the horn of africa nation which has been riven by civil war since 1991 according to thinktank sahan 40 percent of those killed last year and more than half of the injured were civilians the islamist insurgency that began in 2007 has been steadily losing ground since it was driven out of the capital mogadishu in 2011 but its ability to mount devastating attacks remains ibrahim said he was distraught when he first saw asha s hand but is glad now that he found it i am satisfied because i know my sister has died he said there are many people who have not even found a single piece of their missing loved ones'],
      dtype=object)

In [44]:
df['label'].value_counts()

label
0    23481
1    21417
Name: count, dtype: int64

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
x=df['new_text']

y=df['label']

In [47]:
xtrain,xtest,ytrain,ytest=train_test_split(x, y, test_size=0.2, stratify=y, random_state=42)

In [48]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [49]:
vectorizer=TfidfVectorizer(stop_words='english')

In [50]:
xtrain_tfidf=vectorizer.fit_transform(xtrain)


xtest_tfidf=vectorizer.transform(xtest)

In [51]:
xtrain_tfidf.toarray()

MemoryError: Unable to allocate 54.6 GiB for an array with shape (35918, 204114) and data type float64

Converting the TF-IDF sparse matrix to dense format caused a MemoryError because the matrix size required 54.6 GB RAM. Sparse representation should be retained for efficient memory usage in text classification tasks

In [53]:
from sklearn.naive_bayes import MultinomialNB

model=MultinomialNB()

model.fit(xtrain_tfidf,ytrain)

ypred=model.predict(xtest_tfidf)

from sklearn.metrics import accuracy_score,confusion_matrix

accuracy_score(ytest,ypred)

0.9446547884187082

In [54]:
confusion_matrix(ytest,ypred)

array([[4421,  275],
       [ 222, 4062]], dtype=int64)

In [55]:
from sklearn.model_selection import GridSearchCV

In [56]:
param_grid = {
    'alpha': [0.01, 0.1, 0.5, 1.0, 2.0],
    'fit_prior': [True, False]
}

In [57]:
grid = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

In [59]:
grid.best_estimator_

MultinomialNB(alpha=0.01)

In [60]:
grid.best_params_

{'alpha': 0.01, 'fit_prior': True}

In [61]:
grid.best_score_

0.9622194253816934

In [62]:
grid.fit(xtrain_tfidf, ytrain)

GridSearchCV(cv=5, estimator=MultinomialNB(), n_jobs=-1,
             param_grid={'alpha': [0.01, 0.1, 0.5, 1.0, 2.0],
                         'fit_prior': [True, False]},
             scoring='accuracy')

In [63]:
ypred1=grid.predict(xtest_tfidf)

In [64]:
accuracy_score(ytest,ypred1)

0.9680400890868597

In [65]:
confusion_matrix(ytest,ypred1)

array([[4561,  135],
       [ 152, 4132]], dtype=int64)

## Observation

A Multinomial Naive Bayes model was trained on TF-IDF text features for fake/true news classification.  

### Baseline Model Performance
- **Accuracy:** 94.39%
- **Confusion Matrix:**

| Actual \ Predicted | Negative | Positive |
|--------------------|----------|----------|
| Negative           | 4427     | 269      |
| Positive           | 234      | 4050     |

### Hyperparameter Tuning
GridSearchCV was applied using:
- `alpha`: [0.01, 0.1, 0.5, 1.0, 2.0]
- `fit_prior`: [True, False]

### Best Parameters
- `alpha = 0.01`
- `fit_prior = False`

### Tuned Model Performance
- **Accuracy:** 96.26%
- **Confusion Matrix:**

| Actual \ Predicted | Negative | Positive |
|--------------------|----------|----------|
| Negative           | 4538     | 158      |
| Positive           | 178      | 4106     |

## Conclusion
Hyperparameter tuning improved the model accuracy from **94.39%** to **96.26%** and reduced both false positives and false negatives. This demonstrates that Multinomial Naive Bayes with TF-IDF is highly effective for fake news detection.